# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'Reswift Counter' do
  pod 'ReSwift'
  # Pods for Reswift Counter

  target 'Reswift CounterTests' do
    pod 'ReSwift'
    inherit! :search_paths
  end

  target 'Reswift CounterUITests' do
    inherit! :search_paths
  end

end
